services:

  blog_strapi_api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ~/docker/postgressdata/postgresonly/blog_strapi_api:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
